### PR TITLE
Add zsh completion

### PR DESCRIPTION
**Pull request by mikkeloscar**
Adds zsh completion support to drone-cli.

To use, the file `contrib/completion/zsh/_drone` must be installed to `/usr/share/zsh/site-functions/_drone` (linux) or a similar location. I did not add it to `make install` since I'm not sure if this location is correct for other systems e.i. OS X.

Note this depend on `sed` and `awk` in order to format nodes and users output. This could be avoided by simplifying the output of `drone user ls` and `drone node ls` or maybe add a `--porcelain` argument for when running those commands in a script. I don't know what you prefer?

### CODE REVIEW

**Comment by jackspirou** [comment]
:+1:

**Comment by bradrydzewski** [comment]
very cool, do you know how this works with https://github.com/codegangsta/cli#bash-completion ?

**Comment by mikkeloscar** [comment]
@bradrydzewski I didn't know about that, but that's an interesting approach. I'll check out how capable that system is and report back (might take some time).

**Comment by mikkeloscar** [comment]
Ok, I had a look at it and it's indeed useful for making decent bash-completion support. However since zsh has a more powerful completion system compared to bash it will be held back by this approach. A native zsh implementation as provided by this PR is more powerful than an implementation in codegangsta/cli.

I think a good approach would be to use the native zsh completion but add the bash completion support through codegangsta/cli. It's not much work to implement the bash-completion and I would be happy to do it if you think this is a good idea.

**Comment by bradrydzewski** [comment]
yes, if we can get it working with the builtin codegangsta/cli implementation, and then offer a native zsh approach that would be great.

**Comment by mikkeloscar** [comment]
So I tried to use the codegangsta/cli implementation, but quickly realized how broken it actually is. It only sorta works with the example in their README, but that is more by accident than anything. Unfortunately the codegangsta/cli completion system would need to be rewritten before it can be used.

**Pull request closed without merging**
