### PR TITLE
Integrated drone build ps command

### PR DESCRIPTION
**Pull request by tboerger**
A plain build works already pretty well, just for matrix builds it's more complicated because we should print some information about the parent process like the environment variable map? Any ideas? This is so far the output of a simple non-matrix build:

```
Proc #2
Step: clone
State: success

Proc #3
Step: docker
State: success

Proc #4
Step: microbadger
State: success

Proc #5
Step: slack
State: success
```

### CODE REVIEW

**Comment by tboerger** [comment]
Ah, and it's the first step to fix https://github.com/drone/drone-cli/issues/39

**Comment by gtaylor** [comment]
In seeing `drone build ps`, I'd expect it to only return running builds by default (like `docker ps`). In the case of `docker ps`, you pass an `-a` flag to include all containers. Kubernetes does something similar with completed jobs and stopped pods.

I could see any of the following being more consistent:

1. Use a different sub-command name (`list`, `ls`)
1. Make `drone build ps` only return running builds, add a `-a` flag for ALL.

In either case, I think we'd want some way to only show running builds (whether it is the default behavior or not).

**Comment by tboerger** [comment]
This have been suggested by Brad. It just lists the procs for a specific build

**Comment by gtaylor** [comment]
Given that, `list` or `ls` may be worth considering, since `ps` has a different meaning in Docker and Linux.

**Comment by bradrydzewski** [comment]
The thing we have to consider is that `process` does mean something in the context of drone. A process is a container process running under a build. So a build has one or many child processes and the drone API returns process lists and process trees for individual builds.

I definitely understand your point of view, though.

I do wonder if `drone build ps` does somewhat align with docker in that it essentially returns a list of all containers for an individual build.

**Comment by bradrydzewski** [comment]
While we're on the topic of terminology and usability, I should also point out that `drone build` is probably no longer descriptive of drone. It made sense pre-0.4 when we had a build block in the yaml. We should probably look at renaming to `drone pipeline`

**Comment by bradrydzewski** [comment]
Ignore my last comment. Created a separate issue as to not distract from the topic in this thread. Reference https://github.com/drone/drone-cli/issues/65

**Comment by gtaylor** [comment]
Ah, if that's the case I'd be expecting something like `drone build inspect` or `drone build info` or `drone build describe`. 

I think `ps` has too much historical connotation for "look at things that are _currently_ running".

**Comment by tboerger** [comment]
@bradrydzewski so how do we want to continue on that? I just added that in line with the other CLI output. If you prefer some table here I can change the current output. If we want to do that for all commands let's do it in another PR :)

**Comment by tonglil** [comment]
If we stay with `drone build` to refer to individual runs of a pipeline configuration, then this should be `drone step ps` and `drone step ls`

If we use `drone job` to refer to individual runs, then `drone build ls` and `drone build ps`  and `drone build ls` are suitable.

Just my 2¢.

**Comment by tboerger** [comment]
A new step top sub command doesn't really make sense.

**Pull request merged**
