### PR TITLE
Fix build instructions

### PR DESCRIPTION
**Pull request by natlibfi-arlehiko**

### CODE REVIEW

**Comment by WGH-** [comment]
I don't think Go 1.9 is the minimum requirement, since modules appeared around Go 1.11.

Additionally, the script `.drone.sh` appears to build the release binaries for all platforms, which it not something typical user or developer needs.

**Comment by natlibfi-arlehiko** [comment]
> Additionally, the script `.drone.sh` appears to build the release binaries for all platforms, which is not something typical user or developer needs.

Yes, true. However there is no working documentation on how to build the application, so this is a starter at least :)

**Comment by WGH-** [comment]
The `go install ./...` in the current `BUILDING` file still works. Only the `dep` tool is no longer used.

I guess it can be reduced to:
```
1. Install go 1.13 or later
2. Compile and test:

    go install ./...
```

**Comment by tboerger** [comment]
You should take https://github.com/drone/drone/blob/master/BUILDING as an example.

**Comment by natlibfi-arlehiko** [comment]
> You should take https://github.com/drone/drone/blob/master/BUILDING as an example.

But there is no mention of the build script which is needed in this application.

**Comment by tphoney** [comment]
thanks @natlibfi-arlehiko for the pr, the build instructions are now up to date https://github.com/drone/drone-cli/blob/master/BUILDING

**Pull request closed without merging**
