### PR TITLE
Add globals for exec from plaintext secrets YAML

### PR DESCRIPTION
**Pull request by benschumacher**
Allows `drone exec` to use the plaintext of the secrets YAML to populate environment globals for local builds.

### CODE REVIEW

**Comment by gtaylor** [comment]
I'm writing some tooling to wrap drone-cli (most of our non-engineer users don't care what they're using, they just want to do a final test run before pushing) and this would be very useful for that. My wrapper could point to an existing file with variables, or even generate and crap one out into /tmp if it needed to be a dynamic decision.

Will have to stop by again later to read the changes over in more detail, but conceptually I really like this!

**Comment by bradrydzewski** [comment]
LGTM but about to leave for lunch. Will review when I get back!

**Comment by benschumacher** [comment]
Take your time!

**Comment by gtaylor** [comment]
@benschumacher Can I bug you to update this? https://github.com/drone/docs/blob/master/content/devs/cli.md#local-testing

**Comment by benschumacher** [comment]
@gtaylor Absolutely. Will do.

**Comment by gtaylor** [comment]
@benschumacher Did this ever end up happening?

**Pull request merged**
