### PR TITLE
Log purge command

### PR DESCRIPTION
**Pull request by tonglil**
Need to test still, waiting for https://github.com/drone/drone-go/pull/35.
If there is a way to test it without that merge, let me know.

Closes https://github.com/drone/drone-cli/issues/76.

### CODE REVIEW

**Comment by tonglil** [comment]
PTAL @bradrydzewski

**Comment by tonglil** [comment]
Do you need to tag a release of the Go library in order for this to use it?

**Comment by bradrydzewski** [comment]
You can add a revision constraint to the [`Gopkg.toml`](https://github.com/drone/drone-cli/blob/master/Gopkg.toml#L8) and then run `dep ensure` which should update the vendored dependencies.

We should probably use tags, but I think we need to revisit the tagging strategy for drone-go and drone-cli. We were previously trying to use the same tags as drone/drone, but this is not working well in my opinion, since they follow different release schedules.

**Comment by tonglil** [comment]
Alright, just built this locally and tested it, it was able to purge the logs.

image

Let me know if that toml file change is ok.

**Comment by tonglil** [comment]
^ build failure is due to outdated merge ref.

**Comment by bradrydzewski** [comment]
@tonglil hey, sorry, looks like I might have caused a merge conflict when I updated to a newer version of drone-go. Can you update your PR and I can get this merged today? Thanks!!

**Comment by tonglil** [comment]
Updated

**Comment by bradrydzewski** [comment]
awesome, thanks again!

**Pull request merged**
