### PR TITLE
Add backtraces to error starlark command output

### PR DESCRIPTION
**Pull request by thomasf**
and update starlark depdency.

### CODE REVIEW

**Comment by thomasf** [comment]
The same starlark version as in https://github.com/drone/drone-convert-starlark/pull/8

**Comment by tboerger** [comment]
IMHO it should not print multiline errors, but maybe @bradrydzewski got a different opinion.

**Comment by thomasf** [comment]
> IMHO it should not print multiline errors, but maybe @bradrydzewski got a different opinion.

It's often completely useless if it doesn't though. You can get errors like like `update: got NoneType, want iterable` which could be literaly anywhere in your script where you ran update on a dictionary (or a lot of similar cases).

**Comment by thomasf** [comment]
Why should it not print multi line errors?

**Comment by thomasf** [comment]
For reference there is a test in the drone-convert-starlark repository where the error format is tested for..

https://github.com/drone/drone-convert-starlark/pull/8/files#diff-00aa2d840f6c83c3c66e0078bbc6ff42

**Comment by tboerger** [comment]
A library should not print multiline errors, what this package is. That should up to the caller, so IMHO it should return an error type that gets properly handled by the caller.

**Comment by thomasf** [comment]
I guess that prettyStarlarkError could log the stack trace instead of turning it into an error, that would mean that the error will be written twice since the error will be written later in the execution anyways. 

I guess that an important distinction is that drone-cli isn't a library, it's an application and it is handling the error in an end user friendly way.

**Comment by thomasf** [comment]
In the case of the starlark conversion plugin the plugin interface maybe has to be rewritten to support this since the error that is returned is just written to the http response directly. It needs to maybe have check for it an error writer or something like that.. maybe if something like this was supported via an type assertion the http respose writer casn choose the verbose error and it would be backwards compatible

```
interface {
  Error () string
  VerboseError() string
}
```

**Comment by thomasf** [comment]
I am waiting for suggestions how to change this pull request. I have suggested one solution myself but it's no use for me changing it without additional input.  Just saying no without suggesting options is't particulary helpful to me as an contributor and to the end users since working with non trivial starlark scripts currently has horrible UX.

**Comment by tboerger** [comment]
drone-cli itself is not a library, but this package is a library, so imho the calling code should handle a trace print.

**Comment by thomasf** [comment]
I'm still a little bit confused.. While it is not inside an internal pacakge this starlark package feels a lot more like a supporting drone-cli than a general library, for one thing it lacks well written documentation and for most functions documentation at all and there are no tests which IMO is more important than caring about if errors have multi line strings in their returns but enough with the 

**thats enough with the philosophical discussion for now**

The only package that imports this starlark package seems to be the main function in drone-cli which has a very generic look to it. So you think I should add starlark specific error handling code to the return function at the end of main.go ?

**Comment by thomasf** [comment]
Is this better?

**Comment by bradrydzewski** [comment]
thanks for making the updates, this looks good to me.

**Pull request merged**
