### PR TITLE
Add missing ctx values

### PR DESCRIPTION
**Pull request by tkushnir**

### CODE REVIEW

**Comment by tkushnir** [comment]
@bradrydzewski ?

**Comment by eoinmcafee00** [comment]
Hey @tkushnir 
Thank you for your PR. Can you provide some context/description of the change you've made and why please.
Cheers,
Eoin

**Comment by tkushnir** [comment]
Hello @eoinmcafee00 

I'm trying to use `ctx.build.link` and `ctx.build.environment` in my `.drone.yml` file. The build is working fine, but I can not check the file with `drone-cli` on my PC. So these values are needed in `drone-cli` to check the `.drone.yml` file _before_ it is pushed.

**Comment by tkushnir** [comment]
@eoinmcafee00
By the way, may I include new value `ctx.build.debug` to this PR, as it is [already added by you](https://github.com/drone/drone/pull/3082) to `drone/drone` today?

**Pull request merged**
