### PR TITLE
Support providing server and token via ~/.drone.yml file

### PR DESCRIPTION
**Pull request by DCRichards**
## Description

* Added ability to specify `~/.drone.yml` file for providing server address and token, rather than supplying as command line arguments or env vars. This provides an alternative option for those who'd rather not provide or export them each time each time, or would rather not have them in their `~/.bashrc` or equivalent. This is similar to tools such as `npm` with `~/.npmrc` or `aws` with `~/.aws/config`.

* An example `~/.drone.yml` file will be as follows:

  ``` yaml
  server = https://drone.mycompany.com/
  token = ey3894n4nndkd84s
  ```

## Documentation

* Happy to update the documentation separately, should this PR be accepted/suitable for the project.

### CODE REVIEW

**Comment by bradrydzewski** [comment]
The cli currently supports this functionality by reading these parameters from the environment. It will also automatically load an `.env` file from the working directory [1]

```
DRONE_SERVER=...
DRONE_TOKEN=...
```

If you wanted to store these credentials globally you could set the environment variables in a bashrc file or bash_profile file as well. So I think we support this capability today. If you feel this is still insufficient for your use case let's create a github issue to track and discuss possible options. Thanks!

[1] https://github.com/drone/drone-cli/blob/master/drone/main.go#L16

**Comment by tboerger** [comment]
I wish we had profiles. Currently I'm defining an alias for every drone instance I'm working with

**Comment by bradrydzewski** [comment]
@tboerger I think it is a valid use case, let's get an issue created to discuss options

**Comment by bradrydzewski** [comment]
@DCRichards sure thing, created https://github.com/drone/drone-cli/issues/55

**Pull request closed without merging**
