### PR TITLE
Prevents creating blank username with "drone user add". Closes #114.

### LINKED ISSUE #114: "drone user add" appears to create a blank user
Example:

```
$ drone user ls
max-rocket-internet
$ drone user add
Successfully added user
$ drone user ls

max-rocket-internet
$ drone --version
drone version 1.0.5
$
```

🤔

### PR DESCRIPTION
**Pull request by rewanth1997**
Closes #114 .

@bradrydzewski @tboerger Please review it.

### CODE REVIEW

**Comment by bradrydzewski** [comment]
this was actually fixed serverside in 1.2.2, so not sure we need to add any logic to the CLI

the server will return an `invalid username` error which should be printed to the console:
https://github.com/drone/drone/blob/master/handler/api/users/create.go#L59

**Comment by rewanth1997** [comment]
But what if the user wants to use the CLI version of the tool? Will the server-side fix prevent the blank user create operation? I don't think so.

I tried with the latest CLI version and I'm able to create a blank user.

cli

**Comment by bradrydzewski** [comment]
yes, the server should return an error when attempting to create a user with an empty username from the CLI. This improvement was made in Drone server 1.2.2 (so make sure you have the latest version of the software). If the server is not returning an error, this should be fixed in the server, not the CLI.

**Comment by bradrydzewski** [comment]
you can see the API endpoint to create a user invokes the `Validate` function:
https://github.com/drone/drone/blob/master/handler/api/users/create.go#L59

the `Validate` function should return an error if the username is empty. Here are the unit tests for the validate function that test different scenarios:
https://github.com/drone/drone/blob/master/core/user_test.go#L20

if the validate function isn't working as expected, we would likely need to patch the endpoint handler or the validate function (link to both above).

**Comment by rewanth1997** [comment]
I was using 1.0 version of drone. I updated it to 1.2.3 and the `Validate` is working as expected. I hope this change wouldn't be required anymore. Also please close the associated issue i.e #114 as its fixed on the server-side.

**Pull request closed without merging**
