### PR TITLE
Added proper arg usage

### PR DESCRIPTION
**Pull request by tboerger**
## Before

```
# drone-before build approve -h
NAME:
   drone build approve - approve a build

USAGE:
   drone build approve [arguments...]
```

```
# drone-before build stop -h
NAME:
   drone build stop - stop a build

USAGE:
   drone build stop [arguments...]
```

```
# drone-before user ls -h
NAME:
   drone user ls - list all users

USAGE:
   drone user ls [command options] [arguments...]

OPTIONS:
   --format value  format output (default: "{{ .Login }}")
```

## After

```
# drone-after build approve -h
NAME:
   drone build approve - approve a build

USAGE:
   drone build approve <repo/name> <build>
```

```
# drone-after build stop -h
NAME:
   drone build stop - stop a build

USAGE:
   drone build stop <repo/name> [build] [job]
```

```
# drone-after user ls -h
NAME:
   drone user ls - list all users

USAGE:
   drone user ls [command options]

OPTIONS:
   --format value  format output (default: "{{ .Login }}")
```

### CODE REVIEW

**Comment by tboerger** [comment]
@bradrydzewski I just need to know if you like this format or if you prefer `<required-arg>` and `[optional-arg]`.

**Comment by bradrydzewski** [comment]
@tboerger yes, I think `<required-arg>` would be good here :)

**Comment by tboerger** [comment]
> @tboerger yes, I think <required-arg> would be good here :)

Done

**Comment by bradrydzewski** [comment]
thanks :)

**Pull request merged**
